Add options for compilation of swig wrappers.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -274,7 +274,7 @@ PACKAGE_STRING='Lemur 4.2'
 PACKAGE_BUGREPORT='project@lemurproject.org'
 
 ac_unique_file="app/src/RetEval.cpp"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AR SHARED MODULES WITH_SUMMARIZATION WITH_DISTRIB WITH_CLUSTER HOST_OS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AR SHARED JAVAC JAR JAVAINC JAVAHOME WITH_JAVA PHPCONFIG PHPINCLUDE WITH_PHP MCS SWIG WITH_CSHARP WITH_SWIG PHP_SHARED JAVA_SHARED CSHARP_SHARED PHP_SO JAVA_SO CSHARP_SO MODULES WITH_SUMMARIZATION WITH_DISTRIB WITH_CLUSTER HOST_OS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -816,10 +816,20 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-largefile     omit support for large files
+  --enable-php            Enable php shared library generation
+  --enable-csharp         Enable csharp shared library generation
+  --enable-java           Enable java shared library generation
   --enable-distrib        Enable distributed retrieval package
   --enable-summarization  Enable summarization package
   --enable-assert         Enable assert statements in code
   --enable-cluster        Enable cluster package
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-javahome=path       Set location of JAVAHOME
+  --with-php-config=path       Set location of php-config
+  --with-swig=path       Set location of swig executable
 
 Some influential environment variables:
   CC          C compiler command
@@ -3344,12 +3354,32 @@ _ACEOF
 fi
 
      SHARED="-shared -fPIC"
+     PHP_SHARED="-G"
+     PHP_SO=".so"
+     JAVA_SHARED="-G"
+     JAVA_SO=".so"
+     CSHARP_SHARED="-G"
+     CSHARP_SO=".so"
      ;;
    *linux*)
      SHARED="-shared -fPIC"
+     PHP_SHARED="-shared"
+     PHP_SO=".so"
+     JAVA_SHARED="-shared"
+     JAVA_SO=".so"
+     CSHARP_SHARED="-G"
+     CSHARP_SO=".so"
      ;;
    *-*-darwin*)
      SHARED=
+#SWIG_SHARED = -bundle -bundle_loader /var/tmp/indri-2.2/tmp/php-4.4.2/sapi/cli/php
+# have to fix this for php/java bits.
+     PHP_SHARED="-bundle  -undefined suppress -flat_namespace"
+     PHP_SO=".so"
+     JAVA_SHARED="-dynamiclib -framework JavaVM"
+     JAVA_SO=".jnilib"
+     CSHARP_SHARED="-bundle  -undefined suppress -flat_namespace"
+     CSHARP_SO=".so"
      ;;
    *);;
 esac
@@ -4829,6 +4859,375 @@ _ACEOF
 
 
 
+# Check whether --enable-php or --disable-php was given.
+if test "${enable_php+set}" = set; then
+  enableval="$enable_php"
+
+fi;
+if test "$enable_php" = "yes" ; then
+   WITH_SWIG=1
+   WITH_PHP=1
+else
+   WITH_PHP=0
+fi
+# Check whether --enable-csharp or --disable-csharp was given.
+if test "${enable_csharp+set}" = set; then
+  enableval="$enable_csharp"
+
+fi;
+if test "$enable_csharp" = "yes" ; then
+   WITH_SWIG=1
+   WITH_CSHARP=1
+else
+   WITH_CSHARP=0
+fi
+# Check whether --enable-java or --disable-java was given.
+if test "${enable_java+set}" = set; then
+  enableval="$enable_java"
+
+fi;
+if test "$enable_java" = "yes" ; then
+  WITH_SWIG=1
+  WITH_JAVA=1
+else
+  WITH_JAVA=0
+fi
+if test "$enable_java" = "yes" ; then
+
+# Check whether --with-javahome or --without-javahome was given.
+if test "${with_javahome+set}" = set; then
+  withval="$with_javahome"
+  JAVAHOME="$withval"; JAVACBIN=$JAVAHOME/bin/javac; JAVAINCDIR=$JAVAHOME/include; JAR=$JAVAHOME/bin/jar
+else
+  JAVAHOME=
+fi;
+
+   if test -z "$JAVACBIN" ; then
+     for ac_prog in javac
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAVAC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVAC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVAC="$JAVAC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAVAC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+JAVAC=$ac_cv_path_JAVAC
+
+if test -n "$JAVAC"; then
+  echo "$as_me:$LINENO: result: $JAVAC" >&5
+echo "${ECHO_T}$JAVAC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$JAVAC" && break
+done
+
+     for ac_prog in jar
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAR in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAR="$JAR" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAR="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+JAR=$ac_cv_path_JAR
+
+if test -n "$JAR"; then
+  echo "$as_me:$LINENO: result: $JAR" >&5
+echo "${ECHO_T}$JAR" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$JAR" && break
+done
+
+   else
+     JAVAC="$JAVACBIN"
+   fi
+   echo "$as_me:$LINENO: checking for java include file jni.h" >&5
+echo $ECHO_N "checking for java include file jni.h... $ECHO_C" >&6
+   if test -z "$JAVAINCDIR"; then
+     JAVAINCDIR="/usr/j2sdk*/include /usr/local/j2sdk*/include /usr/jdk*/include /usr/local/jdk*/include /opt/j2sdk*/include /opt/jdk*/include /usr/java/include /usr/java/j2sdk*/include /usr/java/jdk*/include /usr/local/java/include /opt/java/include /usr/include/java /usr/local/include/java /usr/lib/java/include /System/Library/Frameworks/JavaVM.framework/Headers/"
+   fi
+   JAVAINC=""
+   for d in $JAVAINCDIR ; do
+     if test -r $d/jni.h ; then
+       echo "$as_me:$LINENO: result: $d" >&5
+echo "${ECHO_T}$d" >&6
+       JAVAINCDIR=$d
+       JAVAINC="-I$d"
+       break
+     fi
+   done
+   if test "$JAVAINC" = "" -o -z "$JAVAC" ; then
+      echo "$as_me:$LINENO: result: not found disabling swig java wrappers" >&5
+echo "${ECHO_T}not found disabling swig java wrappers" >&6
+      WITH_JAVA=0
+      enable_java=no
+   else
+      echo "$as_me:$LINENO: checking for java include file jni_md.h" >&5
+echo $ECHO_N "checking for java include file jni_md.h... $ECHO_C" >&6
+      JAVAMDDIR=`find $JAVAINCDIR -follow -name jni_md.h -print`
+      if test "$JAVAMDDIR" = "" ; then
+	 echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+	 WITH_JAVA=0
+         enable_java=no
+      else
+	 JAVAMDDIR=`dirname $JAVAMDDIR`
+	 JAVAINC="${JAVAINC} -I$JAVAMDDIR"
+	 echo "$as_me:$LINENO: result: $JAVAMDDIR" >&5
+echo "${ECHO_T}$JAVAMDDIR" >&6
+	 WITH_JAVA=1
+      fi
+   fi
+else
+   JAVAC=
+   JAR=
+   JAVAINC=
+   JAVAHOME=
+   WITH_JAVA=0
+fi
+
+
+
+
+
+
+if test "$enable_php" = "yes" ; then
+
+# Check whether --with-php-config or --without-php-config was given.
+if test "${with_php_config+set}" = set; then
+  withval="$with_php_config"
+  PHPCONFIG="$withval"
+else
+  PHPCONFIG=
+fi;
+   if test -z "$PHPCONFIG" ; then
+      # Extract the first word of "php-config", so it can be a program name with args.
+set dummy php-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PHPCONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PHPCONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PHPCONFIG="$PHPCONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PHPCONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PHPCONFIG=$ac_cv_path_PHPCONFIG
+
+if test -n "$PHPCONFIG"; then
+  echo "$as_me:$LINENO: result: $PHPCONFIG" >&5
+echo "${ECHO_T}$PHPCONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+   fi
+   if test "$PHPCONFIG" = ""; then
+      { echo "$as_me:$LINENO: WARNING: $PHPCONFIG not found disabling swig php wrappers" >&5
+echo "$as_me: WARNING: $PHPCONFIG not found disabling swig php wrappers" >&2;}
+      WITH_PHP=0
+      enable_php=no
+      PHPINCLUDE=
+   else
+      echo "$as_me:$LINENO: checking for php includes" >&5
+echo $ECHO_N "checking for php includes... $ECHO_C" >&6
+      PHPINCLUDE=`$PHPCONFIG --includes`
+      echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6
+      WITH_PHP=1
+   fi
+else
+   PHPINCLUDE=
+   WITH_PHP=0
+fi
+
+
+
+if test "$enable_csharp" = yes ; then
+# Extract the first word of "mcs", so it can be a program name with args.
+set dummy mcs; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_MCS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MCS in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MCS="$MCS" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_MCS="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+MCS=$ac_cv_path_MCS
+
+if test -n "$MCS"; then
+  echo "$as_me:$LINENO: result: $MCS" >&5
+echo "${ECHO_T}$MCS" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+fi
+SWIG=
+if test $WITH_SWIG = 1 ; then
+
+# Check whether --with-swig or --without-swig was given.
+if test "${with_swig+set}" = set; then
+  withval="$with_swig"
+  SWIG="$withval"
+fi;
+  if test -z "$SWIG" ; then
+     for ac_prog in swig
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_SWIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $SWIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_SWIG="$SWIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_SWIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+SWIG=$ac_cv_path_SWIG
+
+if test -n "$SWIG"; then
+  echo "$as_me:$LINENO: result: $SWIG" >&5
+echo "${ECHO_T}$SWIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$SWIG" && break
+done
+
+  fi
+else
+  WITH_SWIG=0
+fi
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
 
 
@@ -5584,6 +5983,24 @@ s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
 s,@AR@,$AR,;t t
 s,@SHARED@,$SHARED,;t t
+s,@JAVAC@,$JAVAC,;t t
+s,@JAR@,$JAR,;t t
+s,@JAVAINC@,$JAVAINC,;t t
+s,@JAVAHOME@,$JAVAHOME,;t t
+s,@WITH_JAVA@,$WITH_JAVA,;t t
+s,@PHPCONFIG@,$PHPCONFIG,;t t
+s,@PHPINCLUDE@,$PHPINCLUDE,;t t
+s,@WITH_PHP@,$WITH_PHP,;t t
+s,@MCS@,$MCS,;t t
+s,@SWIG@,$SWIG,;t t
+s,@WITH_CSHARP@,$WITH_CSHARP,;t t
+s,@WITH_SWIG@,$WITH_SWIG,;t t
+s,@PHP_SHARED@,$PHP_SHARED,;t t
+s,@JAVA_SHARED@,$JAVA_SHARED,;t t
+s,@CSHARP_SHARED@,$CSHARP_SHARED,;t t
+s,@PHP_SO@,$PHP_SO,;t t
+s,@JAVA_SO@,$JAVA_SO,;t t
+s,@CSHARP_SO@,$CSHARP_SO,;t t
 s,@MODULES@,$MODULES,;t t
 s,@WITH_SUMMARIZATION@,$WITH_SUMMARIZATION,;t t
 s,@WITH_DISTRIB@,$WITH_DISTRIB,;t t
